// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

import {Script, console2} from "forge-std/Script.sol";
import {XQNTToken} from "../src/XQNTToken.sol";
import {XQNTTeamVesting} from "../src/XQNTTeamVesting.sol";

/// @notice Deploys immutable contracts only. Allocation and liquidity are
/// intentionally separate Safe transactions generated by the repository tool.
contract DeployXQNT is Script {
    function run() external returns (XQNTToken token, XQNTTeamVesting vesting) {
        address distributionSafe = vm.envAddress("DISTRIBUTION_SAFE");
        address teamSafe = vm.envAddress("TEAM_SAFE");
        uint64 launchTimestamp = uint64(vm.envUint("LAUNCH_TIMESTAMP"));

        _enforceLaunchGate();

        vm.startBroadcast();
        token = new XQNTToken(distributionSafe);
        vesting = new XQNTTeamVesting(teamSafe, launchTimestamp);
        vm.stopBroadcast();

        console2.log("XQNT token:", address(token));
        console2.log("Team vesting:", address(vesting));
        console2.log("Distribution Safe:", distributionSafe);
        console2.log("Team Safe:", teamSafe);
        console2.log("Launch timestamp:", launchTimestamp);
    }

    function _enforceLaunchGate() internal view {
        if (block.chainid == 8453) {
            require(
                keccak256(bytes(vm.envOr("XQNT_MAINNET_ACK", string(""))))
                    == keccak256(bytes("LEGAL_SAFE_AUDIT_VERIFIED")),
                "mainnet gate: set exact acknowledgement"
            );
            require(bytes(vm.envOr("LEGAL_ENTITY_NAME", string(""))).length > 3, "mainnet gate: legal entity missing");
            require(
                bytes(vm.envOr("LEGAL_OPINION_SHA256", string(""))).length == 64,
                "mainnet gate: legal opinion digest missing"
            );
            require(
                bytes(vm.envOr("AUDIT_REPORT_SHA256", string(""))).length == 64,
                "mainnet gate: audit report digest missing"
            );
        } else {
            require(block.chainid == 84532 || block.chainid == 31337, "unsupported chain");
        }
    }
}
